version: '3'
services:
  marp:
    image: marpteam/marp-cli
    container_name: marp
    networks:
      - internal
    ports:
      - "37717:37717"
      - "8080:8080"
    environment:
      - LANG=$LANG
    volumes:
      - .:/home/marp/app
    ## Serves an app at localhost:8080 with real-time builds
    command: -s .
    ## Builds a given deck to HTML or given format
    #command: 2021-02-16-gabriela-mistral/slides.md
    #command: 2021-02-16-gabriela-mistral/slides.md --pdf
    #command: 2021-02-16-gabriela-mistral/slides.md --pptx

networks:
  internal:
    driver: bridge
